.PHONY: build help

install: requirements.txt
	pip install -r requirements.txt
activate_env:
	source ./env/bin/activate
deactivate_env:
	deactivate
help:
	@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-10s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m##/[33m/'
